name: p4a2026
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - sqlalchemy
  - pytest
  - pip
  - pip:
    - langchain
    - langchain-core
    - langchain-ollama
    - langchain-openai
    - langchain-anthropic
    - ollama
    - duckdb
    - plotly
    - python-dotenv
    - pymysql
